apiVersion: v1
kind: Pod
metadata:
  name: parse-server
  labels:
    app: parse-server
spec:
  containers:
  - name: parse-server
    image: parse-server:local
    ports:
    - containerPort: 1337
    env: 
    - name: PARSE_SERVER_APPLICATION_ID
      value: "ParseAppID"
    - name: PARSE_SERVER_MASTER_KEY
      value: "thisisthemasterkey"
    - name: PARSE_SERVER_DATABASE_URI
      value: "mongodb://localhost:/test"
    volumeMounts:
    - mountPath: /parse-server/config
      name: config-vol
    - mountPath: /parse-server/cloud
      name: cloud-code-vol
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
  volumes:
  - name: config-vol
    emptyDir: {}
  - name: cloud-code-vol
    emptyDir: {}