apiVersion: apps/v1
kind: Deployment
metadata:
  name: parse-server
spec:
  selector:
    matchLabels:
      run: parse-server
  replicas: 1
  template:
    metadata:
      labels:
        run: parse-server
    spec:
      containers:
      - name: parse-server
        image: parseplatform/parse-server:4.1.0
        ports:
        - containerPort: 30041
        env: 
        - name: PORT
          value: "30041"
        - name: PARSE_SERVER_APPLICATION_ID
          value: "ParseAppID"
        - name: PARSE_SERVER_MASTER_KEY
          value: "thisisthemasterkey"
        - name: PARSE_SERVER_DATABASE_URI
          value: "mongodb://localhost/test"
        volumeMounts:
        - mountPath: /parse-server/config
          name: config-vol
        - mountPath: /parse-server/cloud
          name: cloud-code-vol
      - name: mongo
        image: mongo:4.2.8
        ports:
        - containerPort: 27017
      volumes:
      - name: config-vol
        emptyDir: {}
      - name: cloud-code-vol
        emptyDir: {}